### ISSUE TITLE
Change the fonts and add minute details to article tiles and category tiles.

### ISSUE THREAD

**Issue by Simran1604** [Supr3me-code/Supr3meNews#12]
Hi @Supr3me-code ,
I want to change the fonts of the Title, heading of articles, and the body of articles as well as add minute detailings like a line to separate the article headline from the body for better readability.

After the changes, it would look like this
![image2](https://user-images.githubusercontent.com/72657303/136260801-1d55c96c-6547-44df-a3f9-e27605eefdc8.jpeg)
![image1](https://user-images.githubusercontent.com/72657303/136260806-82c8a2a5-20e6-49b7-9343-567e91edc2d3.jpeg)
.

**Comment by Simran1604** [comment]
Please assign this issue to me.

**Comment by Supr3me-code** [comment]
Hey @Simran1604 

You can make changes to all the elements that you have mentioned apart from the `app title`

Moreover, could you also make the `article tile` responsive i.e. its dimension to change according to the space occupied by the `article description` element. Right now there is space getting wasted on the articles in which the description is small as compared to others.

_psst... you can also do the responsive thing on a new PR if you want an additional PR for the fest_  😉 

Thank you for your valuable suggestions and the upcoming contributions 😸

**Comment by Supr3me-code** [comment]
Yup, looks good! 👍🏽
