### ISSUE TITLE
Search bar

### ISSUE THREAD

**Issue by Supr3me-code** [Supr3me-code/Supr3meNews#6]
Implementing a **search bar** that fetches articles **across categories** based on the **_keywords_** present in their `title`.

**_p.s._** If you are interested in working on this issue then you can post a **claim request**(a simple comment) and the `issue` will be assigned to you. Do **_not_** work on any issue that is not assigned to you

**Comment by westerandr** [comment]
can i be assigned this issue please?

**Comment by westerandr** [comment]
thanks, it looks pretty straight forward. When I pulled the code and ran `flutter pub get`, it modified the pubspec.loc file and some files in the ios folder. As well as added some Podfiles. I wouldn't want this files to be committed. 

I'm on Flutter 2.5.1 and Dart 2.14.2.

**Comment by Supr3me-code** [comment]
The current code base is on `flutter 2.5.2` and `dart 2.14.3`

Those changes won't affect the working of the project and might be caused due to any update on the packages used in the project.

Anyways, make your changes and run it locally, if it runs smoothly then raise your PR, I will test it as well and if all goes well, will merge it

**Comment by westerandr** [comment]
ok awesome thanks, will give it a go and let you know if I come across any difficulties.
